apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{containerName}}
  namespace: did
  labels:
    app: {{containerName}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{containerName}}
  template:
    metadata:
      labels:
        app: {{containerName}}
        fargate: "true"
    spec:
      containers:
      - name: {{containerName}}
        image: {{containerTag}}
        imagePullPolicy: Always
        resources:
          # Since Amazon EKS Fargate runs only one pod per node,
          # all Amazon EKS Fargate pods run with guaranteed priority,
          # so the requested CPU and memory must be equal to the limit.
          # Reference: https://docs.aws.amazon.com/eks/latest/userguide/fargate-pod-configuration.html
          requests:
            memory: "512Mi"
            cpu: "500m"
          # memory: "128Mi"
          # cpu: "5m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: {{containerPort}}
        securityContext:
          capabilities:
            drop:
              - NET_RAW
        {{environmentVariables}}
      {{configMapVolume}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{containerName}}
  namespace: did
spec:
  type: NodePort
  selector:
    app: {{containerName}}
  ports:
    - protocol: TCP
      port: {{containerPort}}
      targetPort: {{containerPort}}
