apiVersion: apps/v1
kind: Deployment
metadata:
  name: uni-registrar-frontend
  namespace: did
  labels:
    app: uni-registrar
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-registrar-frontend
  template:
    metadata:
      labels:
        app: uni-registrar-frontend
    spec:
      containers:
      - name: uni-registrar-frontend
        image: identitydotcom/uni-registrar-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 7082
---
apiVersion: v1
kind: Service
metadata:
  name: uni-registrar-frontend
spec:
  type: NodePort
  selector:
    app: uni-registrar-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 7082
